### PR TITLE
fix: use node20 as GitHub runner

### PR DESCRIPTION
**Pull request by gr2m**
closes #654

### CODE REVIEW

**Comment by lfgcampos** [comment]
@gr2m any plans on merging this?

**Comment by gr2m** [comment]
Huh I have no idea why I didn't ... I'm really busy with other stuff now. If I made you a collaborator, would you help get this merged?

**Comment by lfgcampos** [comment]
@gr2m to be honest, seems like it was already tackled by https://github.com/gr2m/create-or-update-pull-request-action/pull/654 😅

**Comment by gr2m** [comment]
> and I'd say #655 can also be closed and marked as done (or duplicate - your choice)

good catch, thank you 👍🏼

**Pull request closed without merging**
