### PR TITLE
Fix: Typos

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] fixes a few typos in `README.md`

### CODE REVIEW

**Comment by localheinz** [comment]
Builds are probably failing because the `GITHUB_TOKEN` secret is not available for pull requests from forks.

**Comment by gr2m** [comment]
> Builds are probably failing because the GITHUB_TOKEN secret is not available for pull requests from forks.

Correct.

**Comment by localheinz** [comment]
Thank you, @gr2m!

**Pull request merged**
